   [ 
  { sys: { space: [Object],
       id: 'ZOxa50tHpwXV9SIFkKpXz',
       type: 'Entry',
       createdAt: '2020-01-15T23: 16: 54.792Z',
       updatedAt: '2020-01-15T23: 16: 54.792Z',
       environment: [Object],
       revision: 1,
       contentType: [Object],
       locale: 'en-US'
        },
    fields: { meteorID: '2F6WwZhGoRjoc79Sn',
       adminName: 'Intel® Core™ i7 6950K 3.5GHz',
       name:
        'Intel® Core™ i7 6950X Extreme 10 Cores,
            20 Threads,
            3.5 GHz',
       listName1: 'Intel® Core™ i7 6950X Extreme',
       listName2: '10 Cores,
            20 Threads,
            3.5 GHz',
       fishBowlId: 'INTCI76950X',
       slug: 'intel®-core™-i7-6950k-3.5ghz',
       cost: 1895,
       costEquation: '',
       wattage: -175,
       detailDescription:
        'Intel, the Intel Logo, Intel Inside, Intel Core, and Core Inside are trademarks of Intel Corporation in the U.S. and other countries.',
       detailBullets: [Array],
       detailLearnMore: '',
       overrideBuildTime: 0,
       additionalBuildTime: 0,
       tags: [Array],
       type: [Object],
       active: true,
       archived: false,
       archivedDate: 0,
       additionalShippingCost: 0,
       shippingSizeWeight: 0,
       shippingSizeWidth: 0,
       shippingSizeHeight: 0,
       shippingSizeLength: 0
        }
    },
    { sys: { space: [Object],
       id: '74yRKkrX1KCmTrPleWTSmQ',
       type: 'Entry',
       createdAt: '2020-01-14T23: 46: 44.819Z',
       updatedAt: '2020-01-14T23: 46: 44.819Z',
       environment: [Object],
       revision: 1,
       contentType: [Object],
       locale: 'en-US'
        },
    fields: { meteorID: '2F6WwZhGoRjoc79Sn',
       adminName: 'Intel® Core™ i7 6950K 3.5GHz',
       name:
        'Intel® Core™ i7 6950X Extreme 10 Cores,
            20 Threads,
            3.5 GHz',
       listName1: 'Intel® Core™ i7 6950X Extreme',
       listName2: '',
       fishBowlId: 'INTCI76950X',
       slug: 'intel®-core™-i7-6950k-3.5ghz',
       cost: 1895,
       costEquation: '',
       wattage: 0,
       detailDescription:
        'Intel, the Intel Logo, Intel Inside, Intel Core, and Core Inside are trademarks of Intel Corporation in the U.S. and other countries.',
       detailBullets: [Array],
       overrideBuildTime: 0,
       additionalBuildTime: 0,
       tags: [Array],
       type: [Object],
       active: true,
       archived: false,
       archivedDate: 0,
       additionalShippingCost: 0,
       shippingSizeWeight: 0,
       shippingSizeWidth: 0,
       shippingSizeHeight: 0,
       shippingSizeLength: 0
        }
    }
]